# Generated by Django 3.2 on 2023-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='user', max_length=9, verbose_name='Роль'),
        ),
    ]
