# Generated by Django 3.2 on 2023-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230407_1521'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='uq_author_title'),
        ),
    ]
