# Generated by Django 3.2 on 2023-03-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
